import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/SessionWrapper";
import { ToastContainer } from 'react-toastify';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Get me A Cahi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}  bg-[#000000] bg-[radial-gradient(#ffffff33_1px,#00091d_1px)] bg-[size:20px_20px]`}>
        <SessionWrapper>
          <header>
            <Navbar />
          </header>
          <main className="min-h-screen">
            {children}
          </main>
          <footer>
            <Footer />
          </footer>
        </SessionWrapper>
        <ToastContainer/>
      </body>
    </html>
  );
}
